# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6849cfb6b20bbf31bea454d52e08e811233ffd24a71d74373944cef44f6e95940ed9b86ae90dbf02b3af3458687cc6524847cca690ff53bc5f7248604ba01358

test:
  secret_key_base: 3855327bb79c65d8c9e679f462abd206bdd2926b6b3cf9fc9908aa63690037c7067a431863f113ad1b5a4538b71db284e727543b62c8a7471e65401d72fb685f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
